### ISSUE TITLE
Missing definition for vRecordId

### ISSUE THREAD

**Issue by stewstryker** [mgoricki/orclapex-ig-cheat-sheet#5]
Pardon me if this is an obvious, semi-standard variable name, clear to the experienced js programmer, but I'm not one of those.

Could someone please explain where the **vRecordId** variable in the primary .md is defined and gets its value?

**Comment by APEXGru** [comment]
From the docs : "_for models that define an identityField this is the value of the record's identity field or if the records have multiple identity fields this can be an array of ids or a string representation of the combined identity fields as returned by getRecordId. otherwise it is the table (array) index"_ ... 
In PL/SQL terms : the Primary Key value (which is way shorter ;-) ).
